#registration
spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: DWmK6qzyHclStPAlTjkV
            client-secret: x2DO57yIrJ
            scope: email, nickname

# provider
spring.security.oauth2.client.provider.naver.authorization-uri=https://nid.naver.com/oauth2.0/authorize
spring.security.oauth2.client.provider.naver.token-uri=https://nid.naver.com/oauth2.0/token
spring.security.oauth2.client.provider.naver.user-info-uri=https://openapi.naver.com/v1/nid/me
spring.security.oauth2.client.provider.naver.user-name-attribute=response
